language: generic

sudo: required
services:
    - docker


before_install:
    - docker build -t joldfather/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true joldfather/docker-react npm run test
